spring.application.name=Clg_Project_Backend

server.port=8080

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/nexuscsdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=AXUEpzt5VsEABPO8zFT0g/3+A/uWXUbtncFcNP5qNm4=
jwt.issuer=nexusCS

#3-hrs
jwt.expiry=10800000